[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "lorg"
version = "0.1.0"
description = "Shorten URL and print Org-mode link"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["gdshortener>=1.0.1"]

[project.scripts]
lorg = "lorg.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
